"""empty message

Revision ID: 5a43dedbc45d
Revises: 
Create Date: 2020-09-09 20:39:58.745196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a43dedbc45d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### Automatically created the todos table ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
