"""empty message

Revision ID: 6063d2574eb0
Revises: 0e87eb8f342c
Create Date: 2020-09-15 21:38:32.011294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6063d2574eb0'
down_revision = '0e87eb8f342c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_listID_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    op.drop_column('todos', 'listID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('listID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_listID_fkey', 'todos', 'todolists', ['listID'], ['id'])
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
