"""empty message

Revision ID: 9f08874bb748
Revises: ad58cf2f8e39
Create Date: 2020-09-15 19:42:11.295477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f08874bb748'
down_revision = 'ad58cf2f8e39'
branch_labels = None
depends_on = None


 #Made a mistake with the upgrade process and didn't correct the name. Oops.

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_do_list')
    # ### end Alembic commands ###
