"""empty message

Revision ID: d19282381753
Revises: 6063d2574eb0
Create Date: 2020-09-17 18:24:31.066032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19282381753'
down_revision = '6063d2574eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('todolists', 'listName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('listName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todolists', 'name')
    # ### end Alembic commands ###
